name: readme

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - wordle
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: build readme
        run: |
          echo todo

      - name: commit
        run: |
          git add .
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am '📔 Readme update!'
          git push origin main

