name: readme

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  userfetch:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@v2

      - name: userfetch
        uses: userfetch/userfetch-action@v1
        with:
          config: 'userfetch/config.mjs'
          svg: 'userfetch/info.svg'
        env:
          github_token: ${{ secrets.GH_PAT }}

      - name: userfetch
        uses: userfetch/userfetch-action@v1
        with:
          config: 'userfetch/config_light.mjs'
          svg: 'userfetch/info_light.svg'
        env:
          github_token: ${{ secrets.GH_PAT }}

      - name: commit
        run: |
          git add .
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am '🤖 Daily update!'
          git push origin main
