name: wordle

on:
  repository_dispatch:
    types:
      - wordle

jobs:
  wordle:
    runs-on: ubuntu-latest
    steps:
      - name: wait for previous workflows to finish
        uses: ahmadnassri/action-workflow-queue@v1

      - name: wait some more
        run: sleep 3

      - name: setup
        uses: actions/checkout@v2

      - name: wordle
        uses: aryan02420/wordle@main
        with:
          readme: ./README.md
          tag: wreadle
          serverUrl: https://wreadle.02420.dev

      - name: commit
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am '🐛 Wordle update!' | true
          git pull --rebase
          git push
